{{- $environment := (lookup "v1" "ConfigMap" "flux-system" "remote-config").data.environment -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-assignment-app
  namespace: devops-assignment-app
  labels:
    app: devops-assignment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-assignment-app
  template:
    metadata:
      labels:
        app: devops-assignment-app
    spec:
      containers:
      - name: devops-assignment-app
        image: bryan292/devops-assignment-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: APP_ENV
          value: {{ $environment }}